[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "src"
version = "0.0.1"
description = "This is a Repo for Business Forecasting, all code and document included."
authors = [
  { name = "Gordon Lai" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "apache-airflow>=3.3.1",
    "awscli",
    "ipython",
    "jupyterlab",
    "loguru",
    "matplotlib",
    "mkdocs",
    "nbautoexport>=0.5.2",
    "notebook",
    "numpy",
    "pandas",
    "pip",
    "plotly>=7.0.0",
    "pytest",
    "python-dotenv",
    "radian>=0.6.16",
    "rpy2>=3.6.7",
    "ruff",
    "tqdm",
    "typer",
    "yfinance>=1.7.0",
]
requires-python = "~=3.15.0"


[tool.ruff]
line-length = 99
src = ["src"]
include = ["pyproject.toml", "src/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["src"]
force-sort-within-sections = true

